import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Food Order App</title>
        <meta
          name="description"
          content="A food order app generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p className="text-center">Food Order App</p>
    </div>
  );
};

export default Home;
